"""add bill_id and context_snapshot to Chat model

Revision ID: a5210b46d6fa
Revises: a6fd5a392710
Create Date: 2026-03-03 15:08:00.666363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5210b46d6fa'
down_revision = 'a6fd5a392710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('context_snapshot', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_chats_bill_id'), ['bill_id'], unique=False)
        batch_op.create_foreign_key('fk_chats_bill_id', 'bills', ['bill_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chats_bill_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_chats_bill_id'))
        batch_op.drop_column('context_snapshot')
        batch_op.drop_column('bill_id')

    # ### end Alembic commands ###
