"""Add custom api key to user

Revision ID: a6fd5a392710
Revises: c9965602a9a4
Create Date: 2026-03-03 12:44:49.221610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6fd5a392710'
down_revision = 'c9965602a9a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groq_api_key', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('groq_api_key')

    # ### end Alembic commands ###
